/* 
 * This program has been developed by students from the bachelor Computer Science at 
 * Utrecht University within the Software Project course.
 * © Copyright Utrecht University (Department of Information and Computing Sciences)
 * Licensed under the MIT License. See the LICENSE file in the project root for details.
 */

import { useState } from "react";
import AdminLabelledInput from "./admin-input/admin-labelled-input.tsx";
import AdminButton from "./admin-input/admin-button.tsx";

interface Constraint {
    /** whether this field cannot be left empty */
    required?: boolean;
    /** custom validation */
    validate?: (value: unknown, inputConfig: InputType) => ConstraintCheck[] | null; // returns constraints with their outcome or null
}

export type ConstraintCheck = {
    constraint: string, 
    isError: boolean,
    display: boolean
}

interface InputType {
    /** Name of the input element's label, if undefined -> just the key of property */
    label?: string;
    /** name attribute for the input */
    name?: string
    /** Type of HTML input element, if undefined -> "string" */
    inputType?: "text" | "string" | "boolean" | "number" | "dropdown" | "immutable" | "array" | "password" | "registerField" | "email";
    /** For enum type input (maps to dropdown input) */
    enumOptions?: string[];
    /** constraints for this input */
    constraint?: Constraint;
    /** Custom serialization logic, absolutely use sparingly and with care.
     * Setting this property naturally implies no recursion will be done on this property (it is mapped to a simple text field)
     */
    customSerialize?: (value: any) => string;
    /** custom deserialization logic, absolutely use sparingly and with care
     * inverse of customSerialize
     */
    customDeserialize?: (str: string) => any;

    customMutate?: (oldValue: any, newValue: any) => any;
    /**
     * Makes this datastructure recursive.
     * Setting this datastructure's property naturally implies recursion **will** be applied on the property of the relevant object
     * (you gotta make sure the property is actually a recursible type like an array or child object, of course)
     * use with care
     */
    children?: Record<string, InputType>;
    /** give a name to the input section generated by children */
    childrenSectionName?: string;

    /** What type of autocomplete should be used */
    autocomplete?: string;
    /** Displays when field is (still) empty */
    placeholder?: string;
}

interface AdminGenericObjectFormProps<T extends object> {
    /** object for which to generate a form */
    initial: T;
    /**
     * callback function called when submitting form
     * @param item - mutated object
     */
    onSubmit: (item: T) => void;
    /** callback function called when closing form */
    onCancel?: () => void;
    /** text of the submit button */
    commitText?: string;
    /** give a classname, for custom styling of the form */
    className?: string;
    /** an object listing for each property of the generic object how (and in what way) it should
     * map to an input
     * @see InputType
     */
    inputs: Partial<Record<keyof T, InputType>>;

    /** Text of error to display */
    errorMessage: string;
}

/**
 *
 * Intersects two objects. The ordering of the keys in the
 * resulting object is determined by the second object
 *
 * @param obj1 - first object.
 * @param obj2 - second object.
 * @returns the first object with only those keys that were also present on the second object.
 * @todo: perhaps extract this to utils
 */
function intersectObjects<T extends object, U extends object>(obj1: T, obj2: U): Partial<T> {
    const result: Partial<T> = {};
    for (const key in obj2) {
        if (key in obj1) {
            result[key as unknown as keyof T] = obj1[key as unknown as keyof T];
        }
    }
    return result;
}

/**
 *
 * Recursively generates a hierarchy of inputs based on the properties of the input object
 *
 * @param object - The object whose properties we're generating inputs for (and recurse on in case of nested objects).
 * @param inputs - Additional (optional) config for how to render the inputs for each of the object's properties.
 * @param mutateObject - Callback function telling the input element how to mutate the property it is representing on the original object
 * @param recursionPath - The path of properties (& indices) we took to get to this property,
 * needed for the mutateObject function to get back to its property
 * @returns Inputs as React elements
 */
export function RecursiveInputGenerator(
    object: Record<string, unknown>,
    inputs?: Record<string, InputType>,
    mutateObject?: (
        recursionPath: string[],
        value: unknown,
        pass: boolean, // has no errors?
        inputId: number
    ) => void,
    recursionPath: string[] = [],
    idRef: { current: number } = { current: 0 } // Shared counter for input ids
): React.ReactNode[] {
    const keys = Object.keys(object);

    return keys.map((key) => {
        const value = object[key];
        const inputConfig = inputs?.[key];

        // example: { someproperty: [{...}, {...}, {...}, etc.] } -> recurse on each of the objects in the array
        if (
            Array.isArray(value) &&
            inputConfig?.children &&
            inputConfig?.customSerialize === undefined
        ) {
            return (
                <div key={key}>
                    <div className="w-[75%] h-0.5 bg-white mt-10"></div>
                    {inputConfig?.childrenSectionName && (
                        <h1 className="text-white text-2xl first-letter:uppercase mb-5 mt-3 font-bold">
                            {inputConfig.childrenSectionName}
                        </h1>
                    )}
                    {value.map((v, index) => {
                        return (
                            <div className="mt-7" key={index}>
                                {RecursiveInputGenerator(
                                    intersectObjects(v, inputConfig.children!),
                                    inputConfig.children,
                                    mutateObject,
                                    // so, in JS, everything is basically an object, even arrays >:)
                                    // this means indices can be treated as keys of an object
                                    [...recursionPath, key, String(index)],
                                    idRef
                                )}
                            </div>
                        );
                    })}
                </div>
            );
            // example: { someproperty: { ... } } -> recurse on the child-object
        } else if (typeof value === "object" && value !== null && inputConfig?.children) {
            return (
                <>
                    {RecursiveInputGenerator(
                        value as Record<string, unknown>,
                        inputConfig.children,
                        mutateObject,
                        [...recursionPath, key],
                        idRef
                    )}
                </>
            );
            // example: { someproperty: "some text, some more text" } -> base case: the property has an 'atomic' value (e.g. string, number, bool, etc.)
        } else {
            idRef.current++;
            const currentId = idRef.current;

            let value: unknown = object[key];

            const properSerialization: boolean =
                inputConfig?.customSerialize !== undefined &&
                inputConfig?.customDeserialize !== undefined &&
                inputConfig?.customMutate !== undefined;

            if (properSerialization) {
                value = inputConfig!.customSerialize!(object[key]);
            }

            function validate(val: unknown): ConstraintCheck[] {
                const errors: ConstraintCheck[] = [];

                if (inputConfig?.constraint) {
                    const errRequired = {constraint: inputConfig.label + " is required", isError: false, display: false}
                    if (inputConfig.constraint?.required && String(val).length === 0) {
                        errRequired.isError = true;
                    }
                    errors.push(errRequired);

                    if (inputConfig.constraint?.validate) {
                        const error = inputConfig.constraint.validate(val, inputConfig);
                        if (error) 
                            errors.push(...error);
                    }
                }
                return errors;
            }

            return (
                <AdminLabelledInput
                    key={key}
                    inputId={currentId}
                    label={inputConfig?.label ?? String(key)}
                    placeholder={inputConfig?.placeholder}
                    name={inputConfig?.name}
                    type={inputConfig?.inputType ?? "small-text"}
                    value={value}
                    autocomplete={inputConfig?.autocomplete}
                    required = {inputConfig?.constraint?.required}
                    options={inputConfig?.enumOptions}
                    onChange={(v) => {
                        let updatedValue = v;

                        if (properSerialization) {
                            updatedValue = inputConfig!.customDeserialize!(v as string);

                            updatedValue = inputConfig!.customMutate!(object[key], updatedValue);
                        }

                        const errors = validate(v);
                        const pass = !errors.some(e => e.isError);

                        mutateObject?.(
                            [...recursionPath, key],
                            updatedValue,
                            pass,
                            currentId
                        );
                    }}
                    errors={validate(value)}
                />
            );
        }
    });
}

/**
 * Generates form, given a generic object. ALSO USED FOR REGISTER PAGE, NOT IDEAL BUT IT IS WHAT IT IS
 */
function AdminGenericObjectForm<T extends object>(props: AdminGenericObjectFormProps<T>) {
    const [form, setForm] = useState<T>(props.initial);

    const [invalidInputs, setInvalidInputs] = useState(new Set<number>());

    const normalize = (obj) => JSON.stringify(obj, (_, v) => v ?? ""); // Lambda function to set non-existent fields to empty.
    const hasChanged = normalize(form) !== normalize(props.initial); // User can't press (save/create) if no changes are present.

    function handleSubmit(e: React.FormEvent) {
        e.preventDefault();

        if (invalidInputs.size > 0) return;

        props.onSubmit(form);
    }

    return (
        <form name="register" onSubmit={handleSubmit} className = {props.className === null ? "space-y-4 p-4 rounded bg-gray-800" : props.className }>
            {RecursiveInputGenerator(
                intersectObjects(form, props.inputs),
                props.inputs as any,
                (recursionPath, value, pass, id) => {
                    setForm((previousForm) => {
                        // deep copy the current form
                        const clone = structuredClone(previousForm);
                        let currentProperty: any = clone;

                        // follow the recursion path until the second to last property
                        for (let i = 0; i < recursionPath.length - 1; i++) {
                            currentProperty = currentProperty[recursionPath[i]];
                        }

                        let previousValue =
                            currentProperty[recursionPath[recursionPath.length - 1]];

                        // the value of the last property in the recursion path is the one we want to mutate
                        previousValue = value;

                        currentProperty[recursionPath[recursionPath.length - 1]] = previousValue;

                        // if input validation passed for this input
                        if (pass) {
                            setInvalidInputs((prev) => {
                                prev.delete(id);
                                return new Set(prev);
                            });
                        } else {
                            setInvalidInputs((prev) => new Set(prev.add(id)));
                        }

                        return clone;
                    });
                }
            )}
            {/* Error Message */}
            {props.errorMessage && <p className="text-error mt-4">{props.errorMessage}</p>}
            
            {/* submit and cancel button */}
            <div className="flex gap-2 justify-center">
                <AdminButton type="submit" disabled={invalidInputs.size > 0 || !hasChanged}>
                    {props.commitText ?? "Update"}
                </AdminButton>
                {props.onCancel && <AdminButton onClick={props.onCancel}>Cancel</AdminButton>}
            </div>
        </form>
    );
}

export default AdminGenericObjectForm;
