/*
 * This program has been developed by students from the bachelor Computer Science at
 * Utrecht University within the Software Project course.
 * © Copyright Utrecht University (Department of Information and Computing Sciences)
 * Licensed under the MIT License. See the LICENSE file in the project root for details.
 */

using Models;
using AI;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;

namespace API.Services;

/// <summary>
/// Defines AI-related functionality for generating questions
/// and producing feedback based on test results.
/// </summary>
public interface IAIService
{
    /// <summary>
    /// Generates a new question for a given topic using the AI.
    /// </summary>
    /// <param name="topicId">The unique identifier of the topic.</param>
    /// <param name="questionCount">The number of questions to generate (default is 1).</param>
    /// <returns>
    /// An <see cref="Item"/> generated by the AI.
    /// </returns>
    Task<List<Item>> MakeQuestions(int topicId, int questionCount = 1);

    /// <summary>
    /// Generates AI-based feedback for a completed test.
    /// </summary>
    /// <param name="testId">The ID of the test for which feedback is generated.</param>
    /// <returns>
    /// A formatted string containing the AI-generated feedback.
    /// </returns>
    IAsyncEnumerable<string> AiFeedback(int testId);
}

/// <summary>
/// Service responsible for interacting with the AI API,
/// validating AI responses, and converting them into topic entities.
/// </summary>
public class AIService(
    AppDbContext context,
    IFeedbackGen feedbackGen,
    IQuestionGen questionGen,
    AIUtils aiUtils,
    ILogger<AIService> logger) : IAIService
{
    const int maxQuestionTextLength = 3000;

    /// <summary>
    /// Generates new questions for a topic by prompting the AI with a maximim of 3 example questions from the database,
    /// validating the response against a schema, and persisting the result.
    /// </summary>
    /// <param name="topicId">The unique identifier of the topic.</param>
    /// <param name="questionCount">The number of questions to generate (default is 1).</param>
    /// <returns>
    /// A newly created <see cref="Item"/> generated by the AI.
    /// If generation fails, an empty <see cref="Item"/> is returned.
    /// </returns>
    public async Task<List<Item>> MakeQuestions(int topicId, int questionCount = 1)
    {
        string topicName = context.Scopes.Where(t => t.Id == topicId).Select(t => t.Name).First();

        //Take sample question from the DB to use as an example for the AI, to improve the quality of the generated question
        var finalResults = await getExampleQuestions(topicId);

        var aiResponse = await questionGen.GenerateQuestions(topicId, topicName, questionCount, finalResults);

        string schemaJson = aiUtils.GetRoleMessageContent("question_schema.txt", topicId, topicName);

        List<Item> finalItems = new List<Item>();

        try
        {
            JToken items = JToken.Parse(aiResponse);
            JSchema schema = JSchema.Parse(schemaJson);

            foreach (JToken token in items)
            {
                if (!aiUtils.ValidateAiJson(token, schema))
                {
                    logger.LogError($"Failed to validate ai token: {token}");
                    continue;
                }

                Item item = aiUtils.ParseQuestionFromJson(token);

                context.Items.Add(item);
                await context.SaveChangesAsync();
                context.ScopeItems.Add(new ScopeItem { ScopeId = topicId, ItemId = item.Id });
                context.ItemUrns.Add(new ItemUrn { ItemId = item.Id });
                await context.SaveChangesAsync();

                finalItems.Add(item);
            }

            return finalItems;
        }
        catch (Exception e)
        {
            Console.Error.WriteLine($"Error generating AI question: {e.Message}");
            return new List<Item>();
        }
    }

    /// <summary>
    /// Retrieves up to 3 example questions for a given topic from the database to provide context for AI question generation.
    /// </summary>
    /// <param name="topicId">The ID of the topic for which to retrieve example questions.</param>
    /// <returns>A list of example questions for the specified topic. Or an empty list if no examples are found.</returns>
    public async Task<List<Tuple<string, string, List<(string, bool)>, string>>> getExampleQuestions(int topicId)
    {
        var query =
            from items in context.Items
            join topicitems in context.ScopeItems on items.Id equals topicitems.ItemId
            join answer in context.Answers
                on items.Id equals answer.ItemId into answerGroup
            where topicitems.ScopeId == topicId
            && items.QuestionText != null
            && items.Type != null && items.AnswerExplanation != null
            && items.QuestionText.Length <= maxQuestionTextLength
            && items.AnswerExplanation.Length <= maxQuestionTextLength
            select new Tuple<int, string, string, string>
            (
                items.Id,
                items.QuestionText,
                items.Type.ToString(),
                items.AnswerExplanation
            );

        // Pick semi random items
        var count = await query.CountAsync();
        var skip = Random.Shared.Next(0, Math.Max(0, count - 3));
        var queryRes = await query.Skip(skip).Take(3).ToListAsync();

        var finalResults = new List<Tuple<string, string, List<(string, bool)>, string>>();

        foreach (var item in queryRes)
        {
            var answerOptions = await context.Answers.Where(a => a.ItemId == item.Item1).Select(a => new { a.AnswerText, a.Correct }).ToListAsync();
            var answers = answerOptions.Select(a => (a.AnswerText, a.Correct)).ToList();
            finalResults.Add(new Tuple<string, string, List<(string, bool)>, string>(item.Item2, item.Item3, answers, item.Item4));
        }

        if (finalResults.Count == 0)
        {
            Console.Error.WriteLine($"No example questions found for topic {topicId}, using empty example question for AI generation");
            finalResults.Add(new Tuple<string, string, List<(string, bool)>, string>("", "", new List<(string, bool)>(), ""));
        }

        return finalResults;
    }


    /// <summary>
    /// Generates AI-based feedback for a completed test by collecting
    /// all answered questions, correct answers, and explanations,
    /// and submitting them to the AI.
    /// </summary>
    /// <param name="testId">
    /// The ID of the test for which feedback is generated.
    /// </param>
    /// <returns>
    /// A response stream containing the AI-generated feedback.
    /// </returns>
    public async IAsyncEnumerable<string> AiFeedback(int testId)
    {
        var query =
            from userAnswer in context.UserAnswers
            join item in context.Items on userAnswer.ItemId equals item.Id
            join answer in context.Answers.Where(a => a.Correct)
                on item.Id equals answer.ItemId into answerGroup
            from correctAnswer in answerGroup.DefaultIfEmpty()
            where userAnswer.LevelResultId == testId
            select new Tuple<string, string, string, string>
            (
                item.QuestionText,
                userAnswer.Answer,
                item.Type == Item.ItemType.Open
                    ? "This is an open question, no 1 true correct answer, check against answer explanation"
                    : correctAnswer != null
                        ? correctAnswer.AnswerText
                        : string.Empty,
                item.AnswerExplanation
            );

        var results = await query.ToListAsync();

        await foreach (var token in feedbackGen.GenerateFeedback(results))
        {
            yield return token;
        }
    }
}
