/* 
 * This program has been developed by students from the bachelor Computer Science at 
 * Utrecht University within the Software Project course.
 * © Copyright Utrecht University (Department of Information and Computing Sciences)
 * Licensed under the MIT License. See the LICENSE file in the project root for details.
 */

import { render, waitFor, waitForElementToBeRemoved, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it, test, vi } from "vitest";
import QtiAiFeedback from "../../../src/components/qti-player/feedback-page/qti-ai-feedback";
import "@testing-library/jest-dom/vitest";
import type { LevelResponse } from "../../../src/types/level";
import * as aiFetcher from "../../../src/api/ai.ts";

const mockLevel: LevelResponse = {
    levelId: 1,
    itemIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    assessmentXml:
        '<qti-assessment-test xmlns="http://www.imsglobal.org/xsd/imsqtiasi_v3p0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.imsglobal.org/xsd/imsqtiasi_v3p0 https://purl.imsglobal.org/spec/qti/v3p0/schema/xsd/imsqti_asiv3p0p1_v1p0.xsd" identifier="assessment" title="autogenerated-assessment" xml:lang="en-US"><qti-test-part identifier="part-1" navigation-mode="linear" submission-mode="simultaneous"><qti-assessment-section identifier="assessmentSection-1" title="Section 1" visible="true"><qti-assessment-item-ref identifier="item-722" href="/api/qti/get-item/722" /><qti-assessment-item-ref identifier="item-762" href="/api/qti/get-item/762" /><qti-assessment-item-ref identifier="item-247" href="/api/qti/get-item/247" /><qti-assessment-item-ref identifier="item-61" href="/api/qti/get-item/61" /><qti-assessment-item-ref identifier="item-885" href="/api/qti/get-item/885" /><qti-assessment-item-ref identifier="item-2386" href="/api/qti/get-item/2386" /><qti-assessment-item-ref identifier="item-3777" href="/api/qti/get-item/3777" /><qti-assessment-item-ref identifier="item-2187" href="/api/qti/get-item/2187" /><qti-assessment-item-ref identifier="item-671" href="/api/qti/get-item/671" /><qti-assessment-item-ref identifier="item-1036" href="/api/qti/get-item/1036" /></qti-assessment-section></qti-test-part></qti-assessment-test>',
};

vi.mock("react-router-dom", async () => {
    const actual: object = await vi.importActual("react-router-dom");
    return {
        ...actual,
        useNavigate: () => vi.fn(),
    };
});

beforeEach(() => {
    const mockIntersectionObserver = vi.fn().mockImplementation(
        class {
            observe = vi.fn();
            unobserve = vi.fn();
            disconnect = vi.fn();
        } as any
    );
    window.IntersectionObserver = mockIntersectionObserver as unknown as typeof IntersectionObserver;
});

describe("QTI player -> AI feedback", () => {
    it("renders the feedback after the AI feedback fetch resolves", async () => {
        render(<QtiAiFeedback level={mockLevel} />);

        vi.spyOn(aiFetcher, "FetchAiFeedback");

        await waitFor(async () => {
            expect(await screen.findByTestId("feedbackcontainer")).toHaveTextContent(/.+/g);
        });
    });

    it("renders placeholder text before the AI feedback fetch resolves", () => {
        render(<QtiAiFeedback level={mockLevel} />);

        expect(screen.getByTestId("textplaceholder")).toBeTruthy();
    });

    it("removes placeholder text after the AI feedback fetch resolves", async () => {
        render(<QtiAiFeedback level={mockLevel} />);

        const element = screen.getByTestId("textplaceholder");

        vi.spyOn(aiFetcher, "FetchAiFeedback");

        await waitForElementToBeRemoved(element);
    });
});
