/* 
 * This program has been developed by students from the bachelor Computer Science at 
 * Utrecht University within the Software Project course.
 * © Copyright Utrecht University (Department of Information and Computing Sciences)
 * Licensed under the MIT License. See the LICENSE file in the project root for details.
 */

import { useEffect, useRef, useState } from "react";
import type { LevelResponse } from "../../../types/level";
import { FetchAiFeedback } from "../../../api/ai";
import { QtiButton } from "../miscellaneous/qti-buttons";
import { useNavigate } from "react-router-dom";
import Markdown from "react-markdown";
import TextPlaceholderAnimation from "./text-placeholder-animation";
import { flushSync } from "react-dom";
import { usePostHog } from "posthog-js/react";

interface QtiAiFeedbackProps {
    level: LevelResponse;
}

function QtiAiFeedback(props: QtiAiFeedbackProps) {
    const navigate = useNavigate();
    const markdownRef = useRef<HTMLDivElement | null>(null);
    const posthog = usePostHog();

    const [feedback, setFeedback] = useState<string>('');
    const queue = useRef<string[]>([]);
    const anim = useRef(false);

    // Writes the feedback to the state with a small delay between each character to create a "typing" animation effect.
    const writeFeedback = async () => {
        if (anim.current) return;
        anim.current = true;
        while (queue.current.length > 0) {
            for (const char of queue.current.shift()!) {
                flushSync(() => {
                    setFeedback(prev => prev + char);
                });
                await new Promise(resolve => setTimeout(resolve, 2));
            }
        }
        anim.current = false;
    };

    useEffect(() => {
        queue.current = [];
        anim.current = false;

        const run = async () => {
                await FetchAiFeedback(props.level?.levelId, (token) => {
                    queue.current.push(...token);
                    writeFeedback();
                    posthog.capture('feedback_generated');
                }).catch((error) => {
                if ((error as { response?: Response } | undefined)?.response?.status !== 429) {
                    setFeedback("Something went wrong generating feedback :(");
                }
            });
         }

        run();

    }, []);


    useEffect(() => {
        if (!markdownRef.current) return;

        // fade-in stagger animation for the HTML generated by the <Markdown> component.
        // because this is dynamically generated in a way we can't control we
        // listen for DOM changes to implement the animations.
        const mutationObserver = new MutationObserver((mutations) => {
            // for all mutations that we observed do:
            for (const mutation of mutations) {
                // only proceed if the relevant mutation was the addition of more nodes
                if (mutation.type === "childList" && mutation.addedNodes.length > 0) {
                    const delay = 60;

                    // get all child elements of the markdown container
                    let elements = [...markdownRef.current!.children];

                    // also include the nested <li> elements in <ul> lists
                    elements = elements.flatMap((el) => {
                        if (el.nodeName === "UL") {
                            return [...el.children];
                        } else {
                            return [el];
                        }
                    });

                    // add a transitionDelay CSS property to each element
                    // delay is propertional to its order as a child element
                    // add the fade-in CSS class (defined in index.css)
                    elements.forEach((el, index) => {
                        (el as HTMLElement).style.transitionDelay = `${index * delay}ms`;
                        el.classList.add("fade-in");
                    });

                    // attach an IntersectionObserver to each element so that
                    // we only start the fade-in animations if the elements are actually
                    // in view.
                    const observer = new IntersectionObserver(
                        (entries) => {
                            // all elements who just got 'visible'
                            const newlyVisible = entries
                                .filter((e) => e.isIntersecting)
                                .map((e) => e.target as HTMLElement);

                            if (newlyVisible.length === 0) return;

                            // sort the elements in ascending order based on their vertical position
                            // in the document (from top to bottom)
                            newlyVisible.sort(
                                (a, b) =>
                                    a.getBoundingClientRect().top - b.getBoundingClientRect().top
                            );

                            newlyVisible.forEach((el, index) => {
                                // if the element is not already fading in, add
                                // the fade-in-visible class to start the fade in process
                                // also recalculate the transitionDelay in case these elements
                                // got into view much later. This ensures that, for example, the 1000th
                                // element is not stuck on its initial 1000 * delay transition delay.
                                if (!el.classList.contains("fade-in-visible")) {
                                    el.style.transitionDelay = `${index * delay}ms`;
                                    el.classList.add("fade-in-visible");
                                    observer.unobserve(el);
                                }
                            });
                        },
                        // we consider an element as being visible if any part of it
                        // (even just 1 pixel) is scrolled into view.
                        { threshold: 0 }
                    );

                    elements.forEach((el) => observer.observe(el));
                }
            }
        });

        // observe the Markdown's container <div>
        mutationObserver.observe(markdownRef.current, {
            childList: true, // ensure we observe its children
        });

        // cleanup
        return () => {
            mutationObserver.disconnect();
        };
    }, [markdownRef]);

    return (
        <div className="leading-relaxed">
            <h1 className="text-5xl my-6">Feedback</h1>
            {!feedback && <TextPlaceholderAnimation />}

            <div
                // the prose prose-neutral classes override Tailwind's
                // default stylings for basic HTML tags (e.g. headings, paragraphs)
                className="markdown prose prose-neutral max-w-none mb-10"
                ref={markdownRef}
                data-testid="feedbackcontainer"
            >
                {feedback && <Markdown>{feedback}</Markdown>}
            </div>

            <QtiButton variant="yellow" className="mb-2 w-45 2xl:hidden" onClick={() => void navigate("/")}>
                Exit
            </QtiButton>
        </div>
    );
}

export default QtiAiFeedback;
