/*
 * This program has been developed by students from the bachelor Computer Science at
 * Utrecht University within the Software Project course.
 * © Copyright Utrecht University (Department of Information and Computing Sciences)
 * Licensed under the MIT License. See the LICENSE file in the project root for details.
 */

import { render, screen } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import "@testing-library/jest-dom/vitest";
import { QTI } from "../../src/pages/qti";
import * as levelAPI from "../../src/api/level.ts";
import type { LevelResponse } from "../../src/types/level.ts";
import { MemoryRouter } from "react-router-dom";
import { LevelContextProvider, useLevelContext } from "../../src/contexts/level-context.tsx";
import { useEffect } from "react";
import { startQtiTourIfUnseen } from "../../src/components/tours/qti-tour.ts";

vi.mock("../../src/components/qti-player/main-page/qti-player.tsx", () => ({
    default: () => <div data-testid="qti-player">Mock QTI Player</div>,
}));

const mockLevel: LevelResponse = {
    levelId: 1,
    itemIds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    assessmentXml:
        '<qti-assessment-test xmlns="http://www.imsglobal.org/xsd/imsqtiasi_v3p0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.imsglobal.org/xsd/imsqtiasi_v3p0 https://purl.imsglobal.org/spec/qti/v3p0/schema/xsd/imsqti_asiv3p0p1_v1p0.xsd" identifier="assessment" title="autogenerated-assessment" xml:lang="en-US"><qti-test-part identifier="part-1" navigation-mode="linear" submission-mode="simultaneous"><qti-assessment-section identifier="assessmentSection-1" title="Section 1" visible="true"><qti-assessment-item-ref identifier="item-722" href="/api/qti/get-item/722" /><qti-assessment-item-ref identifier="item-762" href="/api/qti/get-item/762" /><qti-assessment-item-ref identifier="item-247" href="/api/qti/get-item/247" /><qti-assessment-item-ref identifier="item-61" href="/api/qti/get-item/61" /><qti-assessment-item-ref identifier="item-885" href="/api/qti/get-item/885" /><qti-assessment-item-ref identifier="item-2386" href="/api/qti/get-item/2386" /><qti-assessment-item-ref identifier="item-3777" href="/api/qti/get-item/3777" /><qti-assessment-item-ref identifier="item-2187" href="/api/qti/get-item/2187" /><qti-assessment-item-ref identifier="item-671" href="/api/qti/get-item/671" /><qti-assessment-item-ref identifier="item-1036" href="/api/qti/get-item/1036" /></qti-assessment-section></qti-test-part></qti-assessment-test>',
};

const TestQTI = () => {
    const { levelResponse, setLevelResponse } = useLevelContext();
    setLevelResponse(mockLevel);

    useEffect(() => {
        console.log(levelResponse);
    }, [levelResponse]);

    return (
        <MemoryRouter>
            <QTI />
        </MemoryRouter>
    );
};

describe("QTI page", () => {
    it("renders mocked QtiPlayer", async () => {
        vi.spyOn(levelAPI, "GetRandomLevel").mockResolvedValue(mockLevel);
        render(
            <LevelContextProvider>
                <TestQTI />
            </LevelContextProvider>
        );

        const player = await screen.findByTestId("qti-player");
        expect(player).toBeInTheDocument();
        expect(player).toHaveTextContent("Mock QTI Player");
    });
});
