﻿/*
 * This program has been developed by students from the bachelor Computer Science at
 * Utrecht University within the Software Project course.
 * © Copyright Utrecht University (Department of Information and Computing Sciences)
 * Licensed under the MIT License. See the LICENSE file in the project root for details.
 */
using System;

/// <summary>
/// This interface defines the contract for generating questions using AI. Implementations of this interface
/// can use different strategies or AI models to create questions based on the provided topic information.
/// </summary>
public interface IQuestionGen
{
    /// <summary>
    /// Generate questions for a specific topic using AI. The implementation should use the provided topic ID and name
    /// to create relevant questions related to the topic.
    /// </summary>
    /// <param name="topicId">The unique identifier of the topic.</param>
    /// <param name="topicName">The human-readable name of the topic.</param>
    /// <param name="questionCount">The number of questions to generate.</param>
    /// <param name="exampleQuestions">A list of example questions to provide as context to the AI, where each example is a tuple containing the question text, correct answer, list of answer options with correctness, and an explanation.</param>
    /// <returns>
    /// A string containg a json with everything needed for an item generated by the AI.
    /// </returns>
    public Task<string> GenerateQuestions(int topicId, string topicName, int questionCount, List<Tuple<string, string, List<(string, bool)>, string>> exampleQuestions);
}
