﻿/*
 * This program has been developed by students from the bachelor Computer Science at
 * Utrecht University within the Software Project course.
 * © Copyright Utrecht University (Department of Information and Computing Sciences)
 * Licensed under the MIT License. See the LICENSE file in the project root for details.
 */
using System;
using AI;

namespace AI.QuestionGen;
/// <summary>
/// Original pipeline for generating AI questions
/// </summary>
public class OriginalQuestionGen(
    IAIAPI aiapi,
    AIUtils aiUtils) : IQuestionGen
{
    /// <summary>
    /// Generate questions for a specific topic using AI. This implementation uses original prompts and prompts it to GPT-5-mini.
    /// </summary>
    /// <param name="topicId">The unique identifier of the topic.</param>
    /// <param name="topicName">The human-readable name of the topic.</param>
    /// <param name="questionCount">The number of questions to generate.</param>
    /// <param name="exampleQuestions">A list of example questions to provide as context to the AI, where each example is a tuple containing the question text, correct answer, list of answer options with correctness, and an explanation.</param>
    /// <returns>
    /// A string containg a json with everything needed for an item generated by the AI.
    /// </returns>
    public async Task<string> GenerateQuestions(int topicId, string topicName, int questionCount, List<Tuple<string, string, List<(string, bool)>, string>> exampleQuestions)
    {
        string questionSystemText = aiUtils.GetRoleMessageContent("question_system_multiple_choice.txt", topicId, topicName);
        string questionUserText = aiUtils.GetRoleMessageContent("question_user.txt", topicId, topicName, questionCount);

        var aiResponse = await aiapi.PromptAI(
            aiUtils.AiQuestion(questionSystemText, questionUserText, exampleQuestions).Result);

        return aiResponse;
    }
}
